name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: ["*"]

jobs:
  call-docker-build:
    uses: ethdevops/workflows/.github/workflows/basic-docker-build.yaml@main
    with:
      build_args: |
        POSTGRES_VERSION=${{ github.ref_type == 'tag' && github.ref_name != 'latest' && startsWith(github.ref_name, 'v') && split(github.ref_name, '-')[0] || '17.4.0' }}
        DEBIAN_VERSION=${{ github.ref_type == 'tag' && github.ref_name != 'latest' && startsWith(github.ref_name, 'v') && split(github.ref_name, '-')[2] || '12' }}
        REVISION=${{ github.ref_type == 'tag' && github.ref_name != 'latest' && startsWith(github.ref_name, 'v') && split(github.ref_name, '-')[3] || 'r19' }}
    secrets:
      docker_registry_user: ${{ secrets.DOCKER_REGISTRY_USER }}
      docker_registry_password: ${{ secrets.DOCKER_REGISTRY_SECRET }}
 
